# Form implementation generated from reading ui file 'D:\Study\Year2\TDLT\C7\DOANCUOIKI\MainWindow6.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow6(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 829)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, -15, 971, 831))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Study\\Year2\\TDLT\\C7\\DOANCUOIKI\\../../../../main6.png"))
        self.label.setObjectName("label")
        self.lineEditNgay = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditNgay.setGeometry(QtCore.QRect(350, 230, 371, 51))
        self.lineEditNgay.setObjectName("lineEditNgay")
        self.lineEditSL = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSL.setGeometry(QtCore.QRect(350, 310, 371, 51))
        self.lineEditSL.setObjectName("lineEditSL")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 410, 371, 51))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButtonDat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDat.setGeometry(QtCore.QRect(790, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDat.setFont(font)
        self.pushButtonDat.setObjectName("pushButtonDat")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 550, 621, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButtonTC = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTC.setGeometry(QtCore.QRect(820, 610, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTC.setFont(font)
        self.pushButtonTC.setObjectName("pushButtonTC")
        self.pushButtoDX = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtoDX.setGeometry(QtCore.QRect(820, 680, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoDX.setFont(font)
        self.pushButtoDX.setObjectName("pushButtoDX")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonDat.setText(_translate("MainWindow", "ĐẶT BÀN"))
        self.pushButtonTC.setText(_translate("MainWindow", "TRANG CHỦ"))
        self.pushButtoDX.setText(_translate("MainWindow", "ĐĂNG XUẤT"))
