# Form implementation generated from reading ui file 'D:\Study\Year2\TDLT\C7\DOANCUOIKI\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 740)
        MainWindow.setStyleSheet("background-image: url(:/image1/2765a25936015eebe3aa05a976978666.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditSDT = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSDT.setGeometry(QtCore.QRect(410, 340, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditSDT.setFont(font)
        self.lineEditSDT.setAutoFillBackground(False)
        self.lineEditSDT.setStyleSheet("\n"
"background-color: rgb(85, 255, 127);")
        self.lineEditSDT.setObjectName("lineEditSDT")
        self.lineEditPW = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPW.setGeometry(QtCore.QRect(410, 410, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPW.setFont(font)
        self.lineEditPW.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lineEditPW.setObjectName("lineEditPW")
        self.pushLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushLogin.setGeometry(QtCore.QRect(510, 490, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushLogin.setFont(font)
        self.pushLogin.setMouseTracking(True)
        self.pushLogin.setObjectName("pushLogin")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 40, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 470, 541, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 350, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 410, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushLogin.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">ẨM THỰC VIỆT</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nếu quý khách quên mật khẩu vui lòng gọi điện cho số điện thoại 091234567 để được hỗ trợ"))
        self.label_3.setText(_translate("MainWindow", "Số điện thoại"))
        self.label_4.setText(_translate("MainWindow", "Mật khẩu"))
