# Form implementation generated from reading ui file 'D:\Study\Year2\TDLT\C7\DOANCUOIKI\MainWindow10.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow10(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 862)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1011, 871))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Study\\Year2\\TDLT\\C7\\DOANCUOIKI\\../../../../main101.png"))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(140, 270, 671, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEditID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditID.setGeometry(QtCore.QRect(520, 620, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditID.setFont(font)
        self.lineEditID.setObjectName("lineEditID")
        self.lineEditST = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditST.setGeometry(QtCore.QRect(520, 670, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditST.setFont(font)
        self.lineEditST.setObjectName("lineEditST")
        self.lineEditID2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditID2.setGeometry(QtCore.QRect(520, 760, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditID2.setFont(font)
        self.lineEditID2.setObjectName("lineEditID2")
        self.pushButtonThem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonThem.setGeometry(QtCore.QRect(840, 630, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonThem.setFont(font)
        self.pushButtonThem.setObjectName("pushButtonThem")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 740, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonThem.setText(_translate("MainWindow", "Thêm"))
        self.pushButton_2.setText(_translate("MainWindow", "XÓA"))
