# Form implementation generated from reading ui file 'D:\Study\Year2\TDLT\C7\DOANCUOIKI\MainWindow7.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow7(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 796)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 941, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Study\\Year2\\TDLT\\C7\\DOANCUOIKI\\../../../../main7real.png"))
        self.label.setObjectName("label")
        self.pushButtonDH = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDH.setGeometry(QtCore.QRect(30, 530, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDH.setFont(font)
        self.pushButtonDH.setObjectName("pushButtonDH")
        self.pushButtonDB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDB.setGeometry(QtCore.QRect(370, 530, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDB.setFont(font)
        self.pushButtonDB.setObjectName("pushButtonDB")
        self.pushButtonKH = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonKH.setGeometry(QtCore.QRect(730, 530, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonKH.setFont(font)
        self.pushButtonKH.setObjectName("pushButtonKH")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 50, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonDH.setText(_translate("MainWindow", "ĐƠN HÀNG"))
        self.pushButtonDB.setText(_translate("MainWindow", "ĐẶT BÀN"))
        self.pushButtonKH.setText(_translate("MainWindow", "KHÁCH HÀNG"))
        self.pushButton_4.setText(_translate("MainWindow", "ĐĂNG XUẤT"))
