# Form implementation generated from reading ui file 'D:\Study\Year2\TDLT\C7\DOANCUOIKI\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 797)
        MainWindow.setStyleSheet("background-image: url(:/image1/2765a25936015eebe3aa05a976978666.jpg);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditSDT = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSDT.setGeometry(QtCore.QRect(380, 390, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditSDT.setFont(font)
        self.lineEditSDT.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEditSDT.setAutoFillBackground(False)
        self.lineEditSDT.setStyleSheet("")
        self.lineEditSDT.setObjectName("lineEditSDT")
        self.lineEditPW = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPW.setGeometry(QtCore.QRect(380, 470, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPW.setFont(font)
        self.lineEditPW.setStyleSheet("")
        self.lineEditPW.setObjectName("lineEditPW")
        self.pushLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushLogin.setGeometry(QtCore.QRect(470, 540, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushLogin.setFont(font)
        self.pushLogin.setMouseTracking(True)
        self.pushLogin.setObjectName("pushLogin")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 1181, 741))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\Study\\Year2\\TDLT\\C7\\DOANCUOIKI\\../../../../main1.png"))
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.lineEditSDT.raise_()
        self.lineEditPW.raise_()
        self.pushLogin.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushLogin.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
